base_images:
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: .ci/openshift-ci/build-root/Dockerfile
  to: eap-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 200Mi
tests:
- as: eap-interop-aws-74
  cron: 0 6 25 10 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      FIREWATCH_CONFIG: ""
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPTOCPCI
      FIREWATCH_JIRA_SERVER: https://issues.redhat.com
      OPERATORS: |
        [
            {"name": "eap", "source": "redhat-operators", "channel": "stable", "version": "2.4.0", "install_namespace": "openshift-operators"}
        ]
      USER_TAGS: |
        scenario eap
    test:
    - ref: install-operators
    - ref: eap-execute-tests
    workflow: firewatch-ipi-aws
zz_generated_metadata:
  branch: 7.4.x
  org: jboss-eap-qe
  repo: openshift-eap-tests
  variant: eap-ocp4.15-lp-interop
