base_images:
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: configmaps-cleanup
  cron: 0 6 25 10 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      FIREWATCH_CONFIG: |
        {
          "failure_rules": []
        }
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTEROP
    test:
    - ref: interop-tests-cleanup-configmaps
    workflow: firewatch-ipi-aws
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: configmaps-cleanup
