base_images:
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    limits:
      memory: 20Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: elastic-search-rosa-aws
  cron: 0 6 25 10 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      FIREWATCH_CONFIG_FILE_PATH: https://raw.githubusercontent.com/CSPI-QE/cspi-utils/main/firewatch-base-configs/rosa/lp-interop.json
      FIREWATCH_DEFAULT_JIRA_ADDITIONAL_LABELS: '["4.14-lp","rosa-classic-lp","elastic-search-lp"]'
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTEROP
      FIREWATCH_FAIL_WITH_TEST_FAILURES: "true"
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.14"
      OPERATORS: |
        [
            {"name": "elasticsearch-operator", "source": "redhat-operators", "channel": "stable-5.8", "install_namespace": "openshift-operators-redhat","target_namespace": "", "operator_group": "openshift-operators-redhat"}
        ]
    test:
    - chain: install-operators
    workflow: firewatch-rosa-aws-sts
zz_generated_metadata:
  branch: main
  org: rhpit
  repo: interop-tests
  variant: elasticsearch-4.14-lp-rosa-classic
