resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: interop-aws-reporter-bot
  cron: 0 0 * * 0
  steps:
    cluster_profile: aws-cspi-qe
    test:
    - ref: mpiit-interop-aws-reporter
zz_generated_metadata:
  branch: develop
  org: rhpit
  repo: interop-aws-reporter
  variant: weekly_trigger
