base_images:
  base:
    name: "4.15"
    namespace: ocp
    tag: base
  cli:
    name: "4.15"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  ocp_4.15_cli:
    name: "4.15"
    namespace: ocp
    tag: cli
  ocs-ci-tests:
    name: ocs-ci-container
    namespace: ci
    tag: stable
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 200Mi
tests:
- as: odf-interop-aws
  cron: 0 6 25 10 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      FIREWATCH_CONFIG: |
        {
        "failure_rules":
        [
          {"step": "aws-provision*", "failure_type": "all", "classification": "Infrastructure Provisioning - AWS", "group": {"name": "cluster", "priority": 1}, "jira_additional_labels": ["!default"]},
          {"step": "aws-deprovision*", "failure_type": "all", "classification": "Infrastructure Deprovisioning - AWS", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
          {"step": "cucushift-*", "failure_type": "all", "classification": "Health Check - Cluster", "group": {"name": "lp-tests", "priority": 2}, "jira_additional_labels":["!default"]},
          {"step": "gather-*", "failure_type": "pod_failure", "classification": "Must Gather - Cluster", "group": {"name": "cluster", "priority": 3}, "jira_additional_labels": ["!default"]},
          {"step": "gather-*", "failure_type": "test_failure", "classification": "NONE", "jira_project": "NONE", "ignore": "true"},
          {"step": "openshift-*", "failure_type": "all", "classification": "Other", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
          {"step": "rosa-cluster-deprovision", "failure_type": "all", "classification": "Infrastructure Deprovisioning - Cluster", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
          {"step": "rosa-cluster-provision", "failure_type": "all", "classification": "Infrastructure Provisioning - Cluster", "group": {"name": "cluster", "priority": 1}, "jira_additional_labels": ["!default"]},
          {"step": "rosa-cluster-wait*", "failure_type": "all", "classification": "Infrastructure Provisioning - Rosa Cluster Operators", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
          {"step": "rosa-sts-account-roles-create", "failure_type": "all", "classification": "Account Roles Creation - AWS", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
          {"step": "rosa-sts-account-roles-delete", "failure_type": "all", "classification": "Account Roles Deletion - AWS", "group": {"name": "cluster", "priority": 3}, "jira_additional_labels": ["!default"]},
          {"step": "rosa-conf-idp-htpasswd", "failure_type": "all", "classification": "Admin Access - Cluster", "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
          {"step": "odf-prepare-cluster", "failure_type": "all", "classification": "Infrastructure Provisioning - Operators", "group": {"name": "lp-tests", "priority": 1}, "jira_additional_labels": ["!default"]},
          {"step": "install-operators", "failure_type": "all", "classification": "Infrastructure Provisioning - Operators", "group": {"name": "lp-tests", "priority": 2}, "jira_additional_labels": ["!default"]},
          {"step": "odf-apply-storage-cluster", "failure_type": "all", "classification": "Infrastructure Provisioning - Operators", "group": {"name": "lp-tests", "priority": 3}, "jira_additional_labels": ["!default"]},
          {"step": "interop-tests-ocs-tests", "failure_type": "pod_failure", "classification": "Test Execution",  "group": {"name": "lp-tests", "priority": 4}, "jira_additional_labels": ["!default","interop-tests"]},
          {"step": "interop-tests-ocs-tests", "failure_type": "test_failure", "classification": "Test Failure", "jira_project": "OCSQE", "group": {"name": "lp-tests", "priority": 4},"jira_additional_labels": ["!default","interop-tests"]}
            ],
          "success_rules":
            [
              {"jira_project": "CSPIT", "jira_additional_labels": ["!default"]}
            ]
        }
      FIREWATCH_DEFAULT_JIRA_ADDITIONAL_LABELS: '["4.15-lp","rosa-classic-lp","odf-lp"]'
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPINTEROP
      FIREWATCH_FAIL_WITH_TEST_FAILURES: "true"
      OCM_LOGIN_ENV: staging
      ODF_VERSION_MAJOR_MINOR: "4.15"
      OPENSHIFT_VERSION: "4.15"
      OPERATORS: |
        [
            {"name": "odf-operator", "install_namespace": "openshift-storage", "target_namespaces": "!install", "operator_group": "openshift-storage-operator-group"}
        ]
    test:
    - ref: odf-prepare-cluster
    - chain: install-operators
    - ref: odf-apply-storage-cluster
    - ref: interop-tests-ocs-tests
    workflow: firewatch-rosa-aws-sts
zz_generated_metadata:
  branch: master
  org: red-hat-storage
  repo: ocs-ci
  variant: odf-ocp4.15-lp-rosa-classic
